"""Build the standalone Talk surfaces using only the Python standard library."""

from __future__ import annotations

import argparse
import json
from pathlib import Path

CSS_TOKEN = "__HERMES_TALK_CSS__"


def read_source(root: Path, relative: str) -> str:
    return (root / relative).read_text(encoding="utf-8").rstrip() + "\n"


def render_bundles(root: Path) -> dict[Path, str]:
    shared = read_source(root, "ui/talk-surface.js")
    dashboard = read_source(root, "ui/dashboard-entry.js")
    banner = "// Generated by scripts/build_ui.py; edit ui/ sources instead.\n"
    bundles = {
        root / "dashboard/dist/index.js": (
            banner + '(function () {\n"use strict";\n\n' + shared + "\n" + dashboard + "})();\n"
        )
    }
    desktop_entry = root / "ui/desktop-entry.js"
    if desktop_entry.is_file():
        desktop = read_source(root, "ui/desktop-entry.js")
        if desktop.count(CSS_TOKEN) != 1:
            raise ValueError("Desktop entry must contain exactly one " + CSS_TOKEN)
        css = (root / "dashboard/dist/style.css").read_text(encoding="utf-8")
        desktop = desktop.replace(CSS_TOKEN, json.dumps(css, ensure_ascii=True))
        view = root / "ui/desktop-view.js"
        desktop_view = read_source(root, "ui/desktop-view.js") if view.is_file() else ""
        bundles[root / "desktop/plugin.js"] = banner + shared + "\n" + desktop_view + "\n" + desktop
    return bundles


def build(root: Path, *, check: bool = False) -> int:
    stale = []
    for path, source in render_bundles(root).items():
        content = source.encode("utf-8")
        if path.is_file() and path.read_bytes() == content:
            continue
        if check:
            stale.append(path.relative_to(root).as_posix())
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_bytes(content)
    if stale:
        print("Stale generated Talk UI: " + ", ".join(stale))
        print("Run python scripts/build_ui.py")
        return 1
    return 0


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check", action="store_true", help="Fail without writing if output differs"
    )
    args = parser.parse_args()
    return build(Path(__file__).resolve().parents[1], check=args.check)


if __name__ == "__main__":
    raise SystemExit(main())
